language: ruby

rvm:
  - 1.9.3

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database drama;' -U postgres
  - psql -c 'create database drama_test;' -U postgres
  - rake db:schema:load
  - rake db:test:prepare
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
