language: ruby

rvm:
  - 1.9.3

before_script:
  - echo 'Setting up database.yml...'
  - cp config/database.travis.yml config/database.yml
  - echo 'Create the databases...'
  - psql -c 'create database drama;' -U postgres
  - psql -c 'create database drama_test;' -U postgres
  - echo 'Load the schema...'
  - rake db:schema:load
  - rake db:test:prepare
  - echo 'Set up XVFB'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
